package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PublishJfrPolyfill'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PublishJfrPolyfill")) {
    params {
        expect {
            password("env.ORG_GRADLE_PROJECT_sonatypePassword", "%mavenCentralStagingRepoPassword%")
        }
        update {
            password("env.ORG_GRADLE_PROJECT_sonatypePassword", "credentialsJSON:047b0669-7dc4-4035-ada8-caca263ab0af")
        }
    }
}
