package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.GRADLE_CACHE_REMOTE_PASSWORD", "%gradle.cache.remote.password%")
        }
        update {
            password("env.GRADLE_CACHE_REMOTE_PASSWORD", "credentialsJSON:911ef8e3-0094-4b96-b688-e0b74b32a644")
        }
    }
}
